export type { ButtonProps } from "./CustomButton";
export { CustomButton as Button } from "./CustomButton";
export type { ColorButtonProps } from "./CustomColorButton";
export { CustomColorButton as ColorButton } from "./CustomColorButton";
export type { SafeAreaViewProps } from "./CustomeSafeAreaView";
export { CustomeSafeAreaView as SafeAreaView } from "./CustomeSafeAreaView";
export type { TextProps } from "./CustomText";
export { CustomText as Text } from "./CustomText";
export type { TextInputProps } from "./CustomTextInput";
export { CustomTextInput as TextInput } from "./CustomTextInput";
export type { ViewProps } from "./CustomView";
export { CustomView as View } from "./CustomView";
